# Generated by Django 2.0b1 on 2017-11-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('legal_id', models.PositiveIntegerField(unique=True, verbose_name='local id')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='report date')),
                ('document_page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='document first page containing table')),
                ('document_page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='document last page containing table')),
                ('finished', models.BooleanField(default=False, verbose_name='object completely translated')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opora.PoliticalParty', verbose_name='related parties')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.PositiveIntegerField(default=1, verbose_name='transaction type')),
                ('money_destination', models.PositiveIntegerField(default=((1, 'political party account'), (2, 'election fund')), verbose_name='money destination')),
                ('local_id', models.PositiveIntegerField(verbose_name='our id')),
                ('page_number', models.PositiveIntegerField(verbose_name='page number containing table with transaction')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='receipt date')),
                ('amount', models.DecimalField(decimal_places='2', max_digits='12', verbose_name='amount')),
                ('total_funds_received', models.DecimalField(decimal_places='2', max_digits='12', verbose_name='total funds received')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opora.PoliticalParty', verbose_name='related parties')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opora.Payee', verbose_name='payee name')),
            ],
        ),
    ]
