# Generated by Django 2.0 on 2017-12-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionpages',
            unique_together={('report', 'money_destination', 'transaction_type', 'legal_identification')},
        ),
    ]
