# Generated by Django 2.0 on 2017-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='legal_id',
            field=models.PositiveIntegerField(verbose_name='local id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='local_id',
            field=models.CharField(max_length=10, verbose_name='our id'),
        ),
    ]
