# Generated by Django 2.0 on 2017-12-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0002_auto_20171207_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places='2', max_digits='12', null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='local_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='our id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money_destination',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='money destination'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='page number containing table with transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opora.Report', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_funds_received',
            field=models.DecimalField(blank=True, decimal_places='2', max_digits='12', null=True, verbose_name='total funds received'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='transaction type'),
        ),
    ]
