# Generated by Django 2.0 on 2018-01-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0002_auto_20171221_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='payee ID or Passport number'),
        ),
    ]
