# Generated by Django 2.0 on 2018-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0003_auto_20180105_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='donation amount'),
        ),
        migrations.AlterField(
            model_name='return',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='donation amount'),
        ),
        migrations.AlterField(
            model_name='return',
            name='amount_to_payee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='return amount to payee'),
        ),
        migrations.AlterField(
            model_name='return',
            name='amount_to_state_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='return amount to state budget'),
        ),
    ]
