# Generated by Django 2.2.5 on 2019-11-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0004_auto_20180105_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(null=True, verbose_name='report date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='opora.PoliticalParty', verbose_name='related parties'),
        ),
    ]
