# Generated by Django 2.2.5 on 2019-11-07 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0006_auto_20191106_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='progress',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
