# Generated by Django 2.2.5 on 2019-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opora', '0007_report_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(max_length=2048, unique=True, verbose_name='report URL'),
        ),
    ]
